version: '3.8'

services:
  email-phishing-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ELASTIC_URL=${ELASTIC_URL:-https://searchsearch-a9ed61.kb.europe-west1.gcp.elastic.cloud}
      - ELASTIC_API_KEY=${ELASTIC_API_KEY}
      - BEDROCK_REGION=${BEDROCK_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
